# build environment
FROM node:13.12.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY backend/graphql/package.json ./
COPY backend/graphql/yarn.lock ./
COPY backend/graphql/index.js ./
COPY decrypt_protected_files.sh ./
COPY .env.gpg ./
RUN env PASSPHRASE=$PROTECTED_FILES_PASSPHRASE sh ./decrypt_protected_files.sh
RUN yarn install --frozen-lockfile --silent
EXPOSE 5433
CMD ["node", "index.js"]