export const API_URL = process.env.NEXT_PUBLIC_SERVER_URL || ''
export const WS_URL = process.env.NEXT_PUBLIC_WS_URL || ''
export const API_KEY = process.env.NEXT_PUBLIC_API_KEY || ''
export const GA_ID = process.env.NEXT_PUBLIC_GA_ID || ''
export const USER = 'trackportfol.io-user'
export const TOKEN = 'trackportfol.io-token'
export const THEME = 'trackportfol.io-theme'
export const DISMISS_UPDATE = 'trackportfol.io-dismiss-update-001'